import { defineStore } from "pinia";

export const userData = defineStore('user2', {
    state: () => ({
       scores: 0,
       isOverlay: false,
       onBottomSheet: false,
       endModal: false,
       cardsData: [
        {value : 'Ace', symbol: 'hearts', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/English_pattern_ace_of_hearts.svg/1365px-English_pattern_ace_of_hearts.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : 'King', symbol: 'hearts', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/English_pattern_king_of_hearts.svg/1200px-English_pattern_king_of_hearts.svg.png', hokm: false, matched: false, isTurned: false, won: false},
        {value : 'Queen', symbol: 'hearts', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/English_pattern_queen_of_hearts.svg/360px-English_pattern_queen_of_hearts.svg.png', hokm: false, matched: false, isTurned: false, won: false},
        {value : 'Jack', symbol: 'hearts', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/English_pattern_jack_of_hearts.svg/1200px-English_pattern_jack_of_hearts.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '10',  symbol: 'hearts', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/English_pattern_10_of_hearts.svg/1365px-English_pattern_10_of_hearts.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '9',  symbol: 'hearts', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/English_pattern_9_of_hearts.svg/1200px-English_pattern_9_of_hearts.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '8',  symbol: 'hearts', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/English_pattern_8_of_hearts.svg/1365px-English_pattern_8_of_hearts.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '7',   symbol: 'hearts', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/English_pattern_7_of_hearts.svg/1200px-English_pattern_7_of_hearts.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '6',  symbol: 'hearts', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/English_pattern_6_of_hearts.svg/800px-English_pattern_6_of_hearts.svg.png', hokm: false, matched: false, isTurned: false, won: false},
        {value : '5',  symbol: 'hearts', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/English_pattern_5_of_hearts.svg/1200px-English_pattern_5_of_hearts.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '4',  symbol: 'hearts', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/English_pattern_4_of_hearts.svg/1365px-English_pattern_4_of_hearts.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '3',  symbol: 'hearts', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/English_pattern_3_of_hearts.svg/1365px-English_pattern_3_of_hearts.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '2',  symbol: 'hearts', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Atlas_deck_2_of_hearts.svg/1200px-Atlas_deck_2_of_hearts.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : 'Ace', symbol: 'spades', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/English_pattern_ace_of_spades.svg/1200px-English_pattern_ace_of_spades.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : 'King', symbol: 'spades', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/English_pattern_king_of_spades.svg/1200px-English_pattern_king_of_spades.svg.png', hokm: false, matched: false, isTurned: false, won: false},
        {value : 'Queen', symbol: 'spades', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/English_pattern_queen_of_spades.svg/1200px-English_pattern_queen_of_spades.svg.png', hokm:false, matched: false, isTurned: false, won: false},
        {value : 'Jack', symbol: 'spades', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/English_pattern_jack_of_spades.svg/1200px-English_pattern_jack_of_spades.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '10',  symbol: 'spades', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/English_pattern_10_of_spades.svg/1200px-English_pattern_10_of_spades.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '9',  symbol: 'spades', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/English_pattern_9_of_spades.svg/540px-English_pattern_9_of_spades.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '8',  symbol: 'spades', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/English_pattern_8_of_spades.svg/360px-English_pattern_8_of_spades.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '7',   symbol: 'spades', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/7_of_spades.svg/1200px-7_of_spades.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '6',  symbol: 'spades', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/English_pattern_6_of_spades.svg/360px-English_pattern_6_of_spades.svg.png', hokm: false, matched: false, isTurned: false, won: false},
        {value : '5',  symbol: 'spades', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/5_of_spades.svg/706px-5_of_spades.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '4',  symbol: 'spades', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/English_pattern_4_of_spades.svg/1365px-English_pattern_4_of_spades.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '3',  symbol: 'spades', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/3_of_spades.svg/1200px-3_of_spades.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '2',  symbol: 'spades', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/English_pattern_2_of_spades.svg/1200px-English_pattern_2_of_spades.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : 'Ace', symbol: 'clubs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/English_pattern_ace_of_clubs.svg/1200px-English_pattern_ace_of_clubs.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : 'King', symbol: 'clubs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/English_pattern_king_of_clubs.svg/360px-English_pattern_king_of_clubs.svg.png', hokm: false, matched: false, isTurned: false, won: false},
        {value : 'Queen', symbol: 'clubs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/English_pattern_queen_of_clubs.svg/1365px-English_pattern_queen_of_clubs.svg.png', hokm: false, matched: false, isTurned: false, won: false},
        {value : 'Jack', symbol: 'clubs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/English_pattern_jack_of_clubs.svg/1365px-English_pattern_jack_of_clubs.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '10',  symbol: 'clubs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/English_pattern_10_of_clubs.svg/682px-English_pattern_10_of_clubs.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '9',  symbol: 'clubs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/English_pattern_9_of_clubs.svg/1365px-English_pattern_9_of_clubs.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '8',  symbol: 'clubs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/8_of_clubs.svg/706px-8_of_clubs.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '7',   symbol: 'clubs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/7_of_clubs.svg/1200px-7_of_clubs.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '6',  symbol: 'clubs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/English_pattern_6_of_clubs.svg/1200px-English_pattern_6_of_clubs.svg.png', hokm: false, matched: false, isTurned: false, won: false},
        {value : '5',  symbol: 'clubs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/English_pattern_5_of_clubs.svg/1200px-English_pattern_5_of_clubs.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '4',  symbol: 'clubs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/English_pattern_4_of_clubs.svg/1200px-English_pattern_4_of_clubs.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '3',  symbol: 'clubs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/English_pattern_3_of_clubs.svg/360px-English_pattern_3_of_clubs.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '2',  symbol: 'clubs', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/English_pattern_2_of_clubs.svg/1200px-English_pattern_2_of_clubs.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : 'Ace', symbol: 'diamonds', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/English_pattern_ace_of_diamonds.svg/1200px-English_pattern_ace_of_diamonds.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : 'King', symbol: 'diamonds', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/English_pattern_king_of_diamonds.svg/1200px-English_pattern_king_of_diamonds.svg.png', hokm: false, matched: false, isTurned: false, won: false},
        {value : 'Queen', symbol: 'diamonds', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/English_pattern_queen_of_diamonds.svg/1200px-English_pattern_queen_of_diamonds.svg.png', hokm: false, matched: false, isTurned: false, won: false},
        {value : 'Jack', symbol: 'diamonds', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/English_pattern_jack_of_diamonds.svg/1200px-English_pattern_jack_of_diamonds.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '10',  symbol: 'diamonds', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/English_pattern_10_of_diamonds.svg/1365px-English_pattern_10_of_diamonds.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '9',  symbol: 'diamonds', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/English_pattern_9_of_diamonds.svg/360px-English_pattern_9_of_diamonds.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '8',  symbol: 'diamonds', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/English_pattern_8_of_diamonds.svg/1365px-English_pattern_8_of_diamonds.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '7',   symbol: 'diamonds', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/English_pattern_7_of_diamonds.svg/360px-English_pattern_7_of_diamonds.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '6',  symbol: 'diamonds', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/English_pattern_6_of_diamonds.svg/1200px-English_pattern_6_of_diamonds.svg.png', hokm: false, matched: false, isTurned: false, won: false},
        {value : '5',  symbol: 'diamonds', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/English_pattern_5_of_diamonds.svg/1200px-English_pattern_5_of_diamonds.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '4',  symbol: 'diamonds', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/English_pattern_4_of_diamonds.svg/682px-English_pattern_4_of_diamonds.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '3',  symbol: 'diamonds', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/English_pattern_3_of_diamonds.svg/1200px-English_pattern_3_of_diamonds.svg.png', hokm: false,matched: false, isTurned: false, won: false},
        {value : '2',  symbol: 'diamonds', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/English_pattern_2_of_diamonds.svg/640px-English_pattern_2_of_diamonds.svg.png', hokm: false,matched: false, isTurned: false, won: false},
    ]
        
    })
})